# Generated by Django 3.1 on 2021-04-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='duration',
            new_name='completed_duration',
        ),
    ]
