# Generated by Django 3.1 on 2021-05-07 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_auto_20210429_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='athletes.athlete'),
        ),
    ]
